### ISSUE TITLE
implement [slug].js "generic" page

### ISSUE THREAD

**Issue by jonathan-chin** [share-meals/food-guide-toolkit-website#28]
- [x] make hero images responsive and keep original aspect ratio
- [x] switch CKEditor to markdown and render maybe using [React Markdown](https://github.com/remarkjs/react-markdown)
- [x] make update time more readable, probably using [React Moment](https://github.com/headzoo/react-moment) or another date utility package
- [x] fix this error: `Warning: Prop `src` did not match. Server: "http://localhost:1337/uploads/stream_starting_soon_d9b7dca817.png" Client: "undefined/uploads/stream_starting_soon_d9b7dca817.png"`

**Comment by ChelleyD** [comment]
Ran into an error while resolving a merge conflict on branch tamika-slug @jonathan-chin .
