### ISSUE TITLE
implement authenticated views

### ISSUE THREAD

**Issue by jonathan-chin** [share-meals/food-guide-toolkit-website#29]
authguards shifted to next development cycle

**Comment by jonathan-chin** [comment]
it seems NextJS supports this out of the box:
https://nextjs.org/docs/authentication

**Comment by ChelleyD** [comment]
This can be used to setup user authentication: https://next-auth.js.org/

**Comment by jonathan-chin** [comment]
since NextAuthJS lets us use third party providers, we won't have the traditional login/signup/reset password pages

**Comment by jonathan-chin** [comment]
working branch at `jon-nextjs-nextauthjs`

- [ ] need to style providers page
- [ ] redesign login / signup workflows
- [ ] continue testing of logged in / logged out views still "flash"
- [ ] find a way to get session data into header because we cannot call `getStaticPageProps` in components
- [ ] if we want to implement Email Provider, need to find a solution for adapters

**Comment by jonathan-chin** [comment]
39168d7 implemented necessary backend changes to support a custom providers page. still need to implement full designs once available.

**Comment by jonathan-chin** [comment]
implemented designs for login page. mostly good. things to look out for:

1. if we add other providers, we might need to lengthen width of buttons. also we'll need to update MUI theme to include the right brand color.
2. probably want to resize `h1` tags in MUI theme.

**Comment by jonathan-chin** [comment]
`jon-nextjs-header-static` branch has a solution for accessing static props in components.
